spring:
  datasource:
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: false
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          driverClassName: com.mysql.jdbc.Driver
          # jdbc 所有参数配置参考
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://localhost:3306/smx_face?useUnicode=true&characterEncoding=utf8&useSSL=false
          username: root
          password: 123456
        # 从库数据源
        slave:
          lazy: true
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/sharding_1?useUnicode=true&characterEncoding=utf8&useSSL=false
          username: root
          password: 123456
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
logging:
  level:
    com.baomidou.mybatisplus.sample: DEBUG
server:
  port: 8090

springdoc:
  group-configs:
    - group: swagger-config
      packages-to-scan: com.practice.bootintegrate


